name: ChatGPT Review

on: [pull_request]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        version: 14
    - name: Build Extension
      run: |
        npm install
        npm run compile
    - name: Smoke test (Linux)
      run: xvfb-run -a npm run test
      if: runner.os == 'Linux'
    - name: Smoke test (Mac, Windows)
      run: npm run test
      if: runner.os != 'Linux'
    - name: Package Extension
      if: matrix.os == 'ubuntu-latest'
      run: |
        npm install -g vsce
        vsce package
        mkdir vsix
        mv *.vsix vsix
    - name: Archive Extension
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v1
      with:
        name: vsix
        path: vsix
  
  chatgpt_review:
    name: ChatGPT
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ChatGPT Reviewer
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
